Add a configuration option to execute commands on startup.
dbcli/pgcli pull request #1294
Opened 2021-11-09 14:27 UTC by mlefebvre

## Description
Related issue: #247 

I needed a way to execute commands on startup (like `SET default_transaction_read_only = on` when connecting on a production server), so I added a new startup_command configuration option.

## Checklist
- [x] I've added this contribution to the `changelog.rst`.
- [x I've added my name to the `AUTHORS` file (or it's already there).
- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

2021-11-19 17:52 UTC, j-bennet requested changes
A unit test for this feature would be helpful. You'd want to test a few use cases:

* single command, valid SQL
* single command, invalid SQL
* multiline command.

For some examples, look at https://github.com/dbcli/pgcli/blob/master/tests/test_main.py.

2022-09-02 21:13 UTC, j-bennet commented
Hi @mlefebvre, I tested your PR, things work fine. If you rebase on main, I'll merge this without a test.

2022-09-02 21:14 UTC, j-bennet approved these changes
Ok to rebase and merge.

2022-09-13 22:14 UTC, mlefebvre commented
Sorry @j-bennet , I had completely forgotten about this!

We found a different way to achieve what we wanted to do, so we didn't need the feature anymore.

2022-09-16 20:42 UTC, j-bennet commented
@mlefebvre

Thank you for getting back to me. If you don't intend to continue working on it, I'll close the PR.

Can you share how you solved this, so other users can benefit from your solution?

2022-09-16 20:42 UTC, closed without merging

2025-04-13 18:23 UTC, danlamanna commented
I'm also curious about solutions others have come up with, I tend to connect and immediately search history so I can run `SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY;`.

2025-06-07 10:03 UTC, danlamanna commented
For others following - this was implemented in #1504 :tada: